header:
  version: 11

machine: thin_client
distro: ahk
target:
  - ahk-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: kirkstone
    layers:
      meta:

  meta-intel:
    url: "git://git.yoctoproject.org/meta-intel"
    branch: kirkstone

  meta-ahk:
    layers:
      meta-ahk:

local_conf_header:
  meta-ahk: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
    BBMASK += "meta-intel/recipes-kernel/linux/"
