header:
  version: 11

machine: thin_client
distro: ahk
target:
  - ahk-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: kirkstone
    layers:
      meta:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    branch: kirkstone
    layers:
      meta-yocto-bsp:

  meta-ahk:
    layers:
      meta-ahk:

local_conf_header:
  meta-ahk: |
    # Use only the local hash equivalence server, without an sstate mirror
    BB_HASHSERVE = "auto"
    BB_HASHSERVE_UPSTREAM = ""
    SSTATE_MIRRORS = ""
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
